import { GROWTH } from '../site/assets/rules.js';
// Benchmark for the relative deal rating: the typical home in every suburb of 1,000+ people, run through the
// same analysis the site uses (20% deposit, the RBA's average new investor variable rate, $120k income, 10-year hold,
// established home bought today). Writes the distribution of verdict scores as 100 quantiles to
// site/assets/deal-bands.js, which engine.verdict() uses to grade a deal against it.
import { readFileSync, writeFileSync } from 'node:fs';
import { analyse, suburbScore } from '../site/assets/engine.js';

const dir = new URL('../site/data/', import.meta.url).pathname;
const d = JSON.parse(readFileSync(`${dir}suburbs.json`, 'utf8'));
const market = JSON.parse(readFileSync(`${dir}market.json`, 'utf8'));
const rba = JSON.parse(readFileSync(`${dir}rba.json`, 'utf8'));
// the same typical rate the site uses everywhere: the RBA's average on new investor variable loans
const rate = rba.actual?.newInvVariable?.at(-1)?.[1] || 6.4;
// verdict() is imported lazily so it runs without bands (absolute points only)
const { verdict } = await import('../site/assets/engine.js');

const scores = [];
for (const r of d.rows) {
  const s = Object.fromEntries(d.cols.map((k, i) => [k, r[i]]));
  if (s.pop < 1000) continue;
  const unit = s.pt === 'u';
  const price = unit ? s.u : s.h;
  const rent = unit ? s.ru : s.rh;
  if (!price || !rent) continue;
  s.sc = { cash: s.sc_cash, momentum: s.sc_momentum, growth: s.sc_growth, demand: s.sc_demand, afford: s.sc_afford, stability: s.sc_stability, risk: s.rsk ?? 0, modelled: !(s.conf === 'high' || s.conf === 'medium') };
  const a = analyse({ state: s.s, price, weeklyRent: rent, deposit: 0.2, ratePct: rate, income: 120000, hold: 10, growth: GROWTH.base, perth: s.rg === 'PER', newBuild: false, strata: unit ? 3200 : 0, landValuePct: unit ? 0.25 : 0.55 });
  scores.push(verdict(a, { ...s, score: suburbScore(s.sc) }, market).score);
}
scores.sort((a, b) => a - b);
const q = Array.from({ length: 100 }, (_, i) => scores[Math.min(scores.length - 1, Math.floor(((i + 0.5) / 100) * scores.length))]);
const out = { built: new Date().toISOString().slice(0, 10), n: scores.length, rate, assumptions: '20% deposit, RBA average new investor variable rate, $120,000 income, 10-year hold, established home bought today', q };
writeFileSync(new URL('../site/assets/deal-bands.js', import.meta.url), `// Generated by scripts/deal_bands.mjs: verdict scores for the typical home in ${scores.length.toLocaleString()} suburbs.\nexport const DEAL_BANDS = ${JSON.stringify(out)};\n`);
console.log(`deal bands: ${scores.length} suburbs, median score ${scores[Math.floor(scores.length / 2)]}, p15 ${q[15]}, p60 ${q[60]}, p85 ${q[85]}`);
